import { StyleSheet } from 'react-native';

export const BG = '#08090F';        // deep space base
export const FG = '#F4F5FB';
export const MUTED = '#8C8EA6';     // cooler grey for secondary text
export const CARD = '#14161F';      // slightly lifted, blue-tinted surface
export const CARD2 = '#1C1F2B';     // higher elevation / pressed states
export const ACCENT = '#D9FF3D';    // signature lime (brand)
export const ACCENT2 = '#8B7BFF';   // violet glow for accents/gradients
export const LINE = '#242739';      // soft violet-tinted hairline


// ---------- Styles ----------
export const s = StyleSheet.create({
  obHeader: { paddingHorizontal:18, paddingTop:8, paddingBottom:14, borderBottomWidth:1, borderBottomColor: LINE },
  stepCount: { color: MUTED, fontSize:12, marginBottom:8, letterSpacing:1, textTransform:'uppercase' },
  obBody: { padding:18, paddingBottom:80 },
  brand: { color: ACCENT, fontSize:42, fontWeight:'900', letterSpacing:-1, marginBottom:8 },
  h1: { color: FG, fontSize:28, fontWeight:'800', marginBottom:8 },
  h2: { color: FG, fontSize:20, fontWeight:'700' },
  pBig: { color: FG, fontSize:16, lineHeight:24 },
  pSm: { color: MUTED, fontSize:13, lineHeight:20 },
  row: { flexDirection:'row', alignItems:'center' },
  rowSb: { flexDirection:'row', alignItems:'center', justifyContent:'space-between', marginBottom:18 },
  label: { color: FG, fontSize:14, fontWeight:'600', marginBottom:8 },
  hint: { color: MUTED, fontSize:12, marginTop:6 },
  input: { backgroundColor: CARD, color: FG, borderRadius:12, paddingHorizontal:14, paddingVertical:14, fontSize:16, borderWidth:1, borderColor: LINE },
  wrap: { flexDirection:'row', flexWrap:'wrap', gap:8 },
  chip: { paddingHorizontal:16, paddingVertical:11, borderRadius:999, borderWidth:1, borderColor: LINE, backgroundColor: CARD, marginRight:8, marginBottom:8 },
  chipSm: { paddingHorizontal:12, paddingVertical:7 },
  chipOn: { backgroundColor: ACCENT, borderColor: ACCENT },
  chipTxt: { color: FG, fontSize:14 },
  chipTxtSm: { fontSize:13 },
  chipTxtOn: { color:'#000', fontWeight:'700' },
  progT: { height:4, backgroundColor: LINE, borderRadius:2, overflow:'hidden' },
  progF: { height:4, backgroundColor: ACCENT },
  obFooter: { flexDirection:'row', alignItems:'center', justifyContent:'space-between', padding:14, paddingBottom:24, borderTopWidth:1, borderTopColor: LINE, backgroundColor: BG, gap:10 },
  btn: { backgroundColor: ACCENT, paddingHorizontal:24, paddingVertical:16, borderRadius:999, flex:1, alignItems:'center' },
  btnDis: { opacity:0.4 },
  btnTxt: { color:'#000', fontWeight:'800', fontSize:15 },
  ghost: { paddingHorizontal:18, paddingVertical:14, borderRadius:999 },
  ghostTxt: { color: FG, fontWeight:'600' },
  topBar: { flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingHorizontal:20, paddingTop:10, paddingBottom:14 },
  brandSm: { color: ACCENT, fontSize:26, fontWeight:'900', letterSpacing:-1 },
  avatar: { width:42, height:42, borderRadius:21, backgroundColor: CARD, alignItems:'center', justifyContent:'center', borderWidth:1, borderColor: LINE },
  avatarTxt: { color: FG, fontWeight:'700' },
  searchRow: { flexDirection:'row', alignItems:'center', paddingHorizontal:20, paddingVertical:12, gap:10 },
  searchBox: { flex:1, backgroundColor: CARD, borderRadius:16, borderWidth:1, borderColor: LINE, paddingHorizontal:16 },
  searchInput: { color: FG, fontSize:16, paddingVertical:15 },
  townieBtn: { backgroundColor: ACCENT, paddingHorizontal:16, paddingVertical:12, borderRadius:12 },
  townieBtnTxt: { color:'#000', fontWeight:'800' },
  summary: { color: MUTED, paddingHorizontal:20, paddingTop:2, paddingBottom:8, fontStyle:'italic', lineHeight:20 },
  center: { flex:1, alignItems:'center', justifyContent:'center', padding:30 },
  emptyTitle: { color: FG, fontSize:18, fontWeight:'700', marginTop:10 },
  emptyTxt: { color: MUTED, fontSize:14, textAlign:'center', marginTop:6 },
  card: { backgroundColor: CARD, borderRadius:24, overflow:'hidden', borderWidth:1, borderColor: LINE },
  cardImg: { width:'100%', height:200, backgroundColor:'#1a1c26' },
  cardBody: { padding:18 },
  tag: { backgroundColor:'#222', paddingHorizontal:8, paddingVertical:4, borderRadius:6 },
  tagTxt: { color: MUTED, fontSize:11, textTransform:'uppercase', letterSpacing:0.5 },
  cardTitle: { color: FG, fontSize:20, fontWeight:'800', letterSpacing:-0.3, marginTop:10, lineHeight:25 },
  cardMeta: { color: MUTED, fontSize:13, marginTop:3 },
  cardDesc: { color: FG, fontSize:14, marginTop:8, lineHeight:20 },
  actSm: { paddingHorizontal:14, paddingVertical:8, borderRadius:999, backgroundColor:'#222' },
  actDetailsTxt: { color: FG, fontSize:13, fontWeight:'700' },
  tabBar: { position:'absolute', bottom:0, left:0, right:0, flexDirection:'row', backgroundColor:'rgba(8,9,15,0.94)', borderTopWidth:1, borderTopColor: LINE, paddingBottom:28, paddingTop:12 },
  tabItem: { flex:1, alignItems:'center', paddingVertical:8 },
  tabLabel: { color: MUTED, fontSize:13, fontWeight:'700', letterSpacing:0.3 },
  detailTitle: { color: FG, fontSize:24, fontWeight:'800' },
  detailMeta: { color: MUTED, fontSize:14, marginTop:4 },
  detailDesc: { color: FG, fontSize:15, lineHeight:22, marginTop:14 },
  detailFooter: { flexDirection:'row', gap:10, padding:14, paddingBottom:24, borderTopWidth:1, borderTopColor: LINE },

  // --- added: sleeker look + new screens ---
  kicker: { color: ACCENT, fontSize:11, fontWeight:'800', letterSpacing:1.5, textTransform:'uppercase', marginBottom:2 },
  subhead: { color: MUTED, fontSize:13, paddingHorizontal:16, paddingTop:2, paddingBottom:6 },
  iconBtn: { width:42, height:42, borderRadius:21, backgroundColor: CARD, alignItems:'center', justifyContent:'center', borderWidth:1, borderColor: LINE, marginRight:10 },
  iconTxt: { color: FG, fontSize:16 },
  sectionTitle: { color: FG, fontSize:16, fontWeight:'800', marginTop:22, marginBottom:12 },
  cardImgFallback: { alignItems:'center', justifyContent:'center', backgroundColor:'#1c1c24' },
  cardImgFallbackTxt: { color: ACCENT, fontSize:54, fontWeight:'900', opacity:0.5 },
  rankBadge: { position:'absolute', top:12, left:12, backgroundColor: ACCENT, paddingHorizontal:10, paddingVertical:5, borderRadius:999 },
  rankTxt: { color:'#000', fontSize:12, fontWeight:'800' },
  heartOverlay: { position:'absolute', top:10, right:10, width:36, height:36, borderRadius:18, backgroundColor:'rgba(0,0,0,0.45)', alignItems:'center', justifyContent:'center' },
  heartOverlayTxt: { color: ACCENT, fontSize:18, fontWeight:'700' },
  invitePill: { backgroundColor: ACCENT, paddingHorizontal:16, paddingVertical:9, borderRadius:999 },
  invitePillTxt: { color:'#000', fontWeight:'800', fontSize:13 },
  igBtn: { backgroundColor:'#C13584', borderRadius:12, paddingVertical:14, alignItems:'center', marginTop:12 },
  igBtnTxt: { color:'#fff', fontWeight:'800', fontSize:15 },
  friendRow: { flexDirection:'row', alignItems:'center', paddingVertical:12, borderBottomWidth:1, borderBottomColor: LINE, gap:12 },
  friendAvatar: { width:46, height:46, borderRadius:23, backgroundColor: CARD, borderWidth:1.5, borderColor: ACCENT, alignItems:'center', justifyContent:'center' },
  friendName: { color: FG, fontSize:16, fontWeight:'700' },
  goingPill: { borderWidth:1, borderColor:'#2e7d32', borderRadius:999, paddingHorizontal:12, paddingVertical:6 },
  goingTxt: { color:'#5dd15d', fontWeight:'700', fontSize:12 },
  vipHero: { backgroundColor: CARD, borderRadius:20, borderWidth:1, borderColor: LINE, padding:20 },
  vipHeroTitle: { color: FG, fontSize:24, fontWeight:'900', letterSpacing:-0.5 },
  vipHeroSub: { color: MUTED, fontSize:14, lineHeight:21, marginTop:8 },
  vipRow: { flexDirection:'row', alignItems:'flex-start', gap:10, marginBottom:10 },
  vipCheck: { color: ACCENT, fontWeight:'900', fontSize:15 },
  vipRowTxt: { color: FG, fontSize:14, flex:1, lineHeight:20 },
  vipCard: { backgroundColor: CARD, borderRadius:20, borderWidth:1, borderColor: LINE, padding:20 },
  vipCardTitle: { color: FG, fontSize:18, fontWeight:'800' },
  vipCardSub: { color: MUTED, fontSize:14, lineHeight:21, marginTop:6, marginBottom:14 },
  vipPriceRow: { flexDirection:'row', alignItems:'baseline', marginBottom:14 },
  vipPrice: { color: ACCENT, fontSize:32, fontWeight:'900' },
  vipPriceUnit: { color: MUTED, fontSize:14 },
  vipNote: { color: MUTED, fontSize:11, marginTop:12, textAlign:'center' },
  sheetWrap: { flex:1, justifyContent:'flex-end', backgroundColor:'rgba(0,0,0,0.55)' },
  sheet: { backgroundColor: BG, borderTopLeftRadius:22, borderTopRightRadius:22, borderWidth:1, borderColor: LINE, padding:22, paddingBottom:34 },
  errTxt: { color:'#ff6b6b', fontSize:13, marginTop:10 },
  codeBig: { color: ACCENT, fontSize:34, fontWeight:'900', letterSpacing:4, marginVertical:6 },
  // --- Discover swipe layout ---
  toniePill: { backgroundColor: CARD, borderWidth:1, borderColor: ACCENT, borderRadius:18, paddingHorizontal:16, paddingVertical:15, justifyContent:'center' },
  toniePillTxt: { color: ACCENT, fontWeight:'800', fontSize:14 },
  swipeCard: { flex:1, backgroundColor: CARD, borderRadius:28, overflow:'hidden', borderWidth:1, borderColor:'rgba(139,123,255,0.35)', marginBottom:16 },
  swipeImg: { width:'100%', flex:1, minHeight:150, backgroundColor:'#1a1c26' },
  swipeBody: { padding:16 },
  catChip: { backgroundColor:'rgba(217,255,61,0.14)', borderWidth:1, borderColor: ACCENT, borderRadius:999, paddingHorizontal:12, paddingVertical:5, marginRight:8, marginBottom:6 },
  catChipTxt: { color: ACCENT, fontSize:12, fontWeight:'700' },
  matchChip: { backgroundColor: ACCENT, borderRadius:999, paddingHorizontal:12, paddingVertical:5, marginBottom:6 },
  matchChipTxt: { color:'#000', fontSize:12, fontWeight:'800' },
  swipeTitle: { color: FG, fontSize:23, fontWeight:'800', letterSpacing:-0.4, marginTop:2, lineHeight:28 },
  swipeMeta: { color: MUTED, fontSize:14, marginTop:6 },
  swipeDesc: { color: MUTED, fontSize:13.5, fontStyle:'italic', marginTop:6, lineHeight:19 },
  swipeActions: { flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingBottom:8, gap:14 },
  swipeBtn: { width:64, height:64, borderRadius:32, alignItems:'center', justifyContent:'center', borderWidth:1, borderColor: LINE },
  swipeNo: { backgroundColor: CARD },
  swipeYes: { backgroundColor: CARD },
  swipeBtnIcon: { fontSize:26 },
  detailsBtn: { flex:1, backgroundColor: CARD, borderWidth:1, borderColor:'rgba(139,123,255,0.35)', borderRadius:999, paddingVertical:15, alignItems:'center' },
  detailsBtnTxt: { color: FG, fontWeight:'700', fontSize:15 },
  detailNote: { color: ACCENT, fontSize:14, fontStyle:'italic', marginTop:6, lineHeight:20 },
  detailSection: { color: FG, fontSize:15, fontWeight:'800', marginTop:18, marginBottom:4 },
  detailRow: { flexDirection:'row', alignItems:'flex-start', gap:8, marginTop:6 },
  detailIcon: { fontSize:14, width:22 },
  detailMetaBig: { color: FG, fontSize:15, flex:1, lineHeight:21 },
  // --- swipe gesture chrome ---
  swipeCardUnder: { position:'absolute', top:0, left:0, right:0, bottom:0, transform:[{scale:0.96}], opacity:0.55 },
  swipeStamp: { position:'absolute', top:24, paddingHorizontal:14, paddingVertical:6, borderWidth:3, borderRadius:10, transform:[{rotate:'-14deg'}] },
  stampLike: { left:18, borderColor:'#5dd15d' },
  stampLikeTxt: { color:'#5dd15d', fontSize:28, fontWeight:'900', letterSpacing:2 },
  stampNope: { right:18, borderColor:'#ff6b6b', transform:[{rotate:'14deg'}] },
  stampNopeTxt: { color:'#ff6b6b', fontSize:28, fontWeight:'900', letterSpacing:2 },
  swipeHint: { color: MUTED, fontSize:12, textAlign:'center', paddingBottom:2, marginTop:6 },
  linkBtn: { marginTop:18, backgroundColor: ACCENT, borderRadius:12, paddingVertical:14, alignItems:'center' },
  linkBtnTxt: { color:'#000', fontWeight:'800', fontSize:15 },
  // --- cosmic backdrop (pure Views, no native deps) ---
  cosmicWrap: { position:'absolute', top:0, left:0, right:0, bottom:0, overflow:'hidden', backgroundColor: BG },
  nebula: { position:'absolute', width:320, height:320, borderRadius:160 },
  star: { position:'absolute', backgroundColor:'#FFFFFF' },
});
